### ISSUE TITLE
DefaultMailbox.processMessages function is bad written on many levels

### ISSUE THREAD

**Issue by vasily-kirichenko** [AsynkronIT/protoactor-kotlin#1]
https://github.com/AsynkronIT/protoactor-kotlin/blob/master/src/main/kotlin/se/asynkron/proto/mailbox/DefaultMailbox.kt#L44

**Comment by rogeralsing** [comment]
This is currently transpiled from C# mostly, feel free to send PR

**Comment by orjan** [comment]
@vasily-kirichenko would you mind giving us some feedback on the mailbox?
 https://github.com/AsynkronIT/protoactor-kotlin/blob/master/proto-mailbox/src/main/kotlin/actor/proto/mailbox/DefaultMailbox.kt

**Comment by vasily-kirichenko** [comment]
Sorry, I don’t use Kotlin anymore and completely forget what I meant :(
