### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by imkow** [AsynkronIT/protoactor-kotlin#45]
ATS

**Comment by viniciusccarvalho** [comment]
Would like to know too, looks like it may be, huge period without commits, but the go project is still very active

**Comment by james-cobb** [comment]
Not active in terms of commits. But we're using protoactor-kotlin in our production code, so I wouldn't describe the project as dead.  We have very little time to contribute to the project, but have done so in the past, and will do again in the future...

**Comment by imkow** [comment]
@james-cobb out of curiosity. what organization are you working for? 😂

**Comment by james-cobb** [comment]
Crowd Connected.

Actor architecture allows to do cooperative localisation with moving devices in real time, and at scale.

https://www.crowdconnected.com/blog/cooperative-positioning-engine-reaches-general-availability/

**Comment by rogeralsing** [comment]
Hello :-)

One of the reasons this have gone stale, there never was that much community interest for the JVM version here.
Maybe because of Akka and other options.

Once Kotlin coroutines went live, there was a fair amount of changes to the API.
And TBH I wasn't able to upgrade the older codebase to the latest API changes.

So that would be a first step to get this more active, everyone helps out to upgrade to latest Kotlin API's first.

**Comment by james-cobb** [comment]
Will certainly help with that - we need to udpate our own codebase to use the new coroutine API, and we can work on protoactor at the same time...

**Comment by james-cobb** [comment]
@rogeralsing Looks like you did all this work in December -  the latest master branch builds and all tests pass. Just needed to add one gradle dependency, that maybe had been left off the commits:

compile group: 'org.jetbrains.kotlinx', name: 'kotlinx-coroutines-core', version: '1.1.1'

Was there anything else outstanding for the kotlin upgrade?

**Comment by rogeralsing** [comment]
I'm not 100% sure on the status of those patches, IIRC there was some tests that stopped working and was disabled.

**Comment by james-cobb** [comment]
I took a better look. There was some code commented out that used the asCompletableFuture method - needs import of the kotlinx-coroutines-jdk8 library, then it compiles fine.

And there was a test disabled for default supervision strategy that relates to a change of default from One to One to Always.

I can go through carefully again and tidy up any remaining kotlin version / coroutine  issues. and make a PR.

Not sure about the changes to the default strategy which break the test Should revert to default directive when escalate directive without grand parent.

**Comment by asomov** [comment]
Should this issue be closed to avoid confusion ?

**Comment by orjan** [comment]
We should probably explain in the readme that it's an [![experimental](http://badges.github.io/stability-badges/dist/experimental.svg)](http://github.com/badges/stability-badges) jvm version of proto actor.

**Comment by james-cobb** [comment]
We're still using protoactor-kotlin in production...
