### ISSUE TITLE
Failing Unit Test

### ISSUE THREAD

**Issue by vito-c** [AsynkronIT/protoactor-kotlin#46]
```
actor.proto.tests.ActorTests > actorStartedException STANDARD_ERROR
    [DefaultDispatcher-worker-4 @coroutine#29] WARN actor.proto.ActorContext - Handling root failure for nonhost/$9
    [DefaultDispatcher-worker-4 @coroutine#31] WARN actor.proto.ActorContext - Handling root failure for nonhost/$9

actor.proto.tests.ActorTests > actorStartedException STANDARD_OUT
        actor.proto.Started@406769a0
        actor.proto.Restarting@1d184d59
        actor.proto.Started@406769a0
        actor.proto.Stopping@59d6b7fc
        actor.proto.Stopped@523aa1c
        actor.proto.Restarting@1d184d59
        actor.proto.Started@406769a0
        hello

actor.proto.tests.ActorTests > actorStartedException FAILED
    java.lang.AssertionError: expected same:<actor.proto.Restarting@1d184d59> was not:<actor.proto.Stopping@59d6b7fc>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotSame(Assert.java:828)
        at org.junit.Assert.assertSame(Assert.java:771)
        at kotlin.test.junit.JUnitAsserter.assertSame(JUnitSupport.kt:40)
        at kotlin.test.AssertionsKt__AssertionsKt.assertSame(Assertions.kt:58)
        at kotlin.test.AssertionsKt.assertSame(Unknown Source)
        at kotlin.test.AssertionsKt__AssertionsKt.assertSame$default(Assertions.kt:57)
        at kotlin.test.AssertionsKt.assertSame$default(Unknown Source)
        at actor.proto.tests.ActorTests.actorStartedException(ActorTests.kt:107)
```

I'm looking at the failing unit test and I dumped the messages as well (above). It looks like a legit issue to me due to the ordering of the messages.

**Comment by james-cobb** [comment]
I think that's a test I added. What release or branch are you using? Test passes for me when I run locally.

**Comment by vito-c** [comment]
I was using master. Is there a preferred branch I could use? :)

**Comment by james-cobb** [comment]
Master branch includes commits to update kotlin version, there are issues with this that I'm looking at. I have to add an additional dependency (below)  to get the master branch to build locally, but then the actorStartedException test passes fine.

compile group: 'org.jetbrains.kotlinx', name: 'kotlinx-coroutines-core', version: '1.1.1'

I would try going back to commit b6cae1f which IIRC is stable.

**Comment by orjan** [comment]
@james-cobb would this pr bring the project up to speed? https://github.com/AsynkronIT/protoactor-kotlin/pull/44

**Comment by vito-c** [comment]
I wonder why the mutable list wasn't preserving order but the queue was. I have a couple days to look at this. Anything I could do to help out? @rogeralsing (disclosure I'm new to kotlin)

**Comment by james-cobb** [comment]
@orjan Looks like that PR would fix the intermittent problem with this very test. But I think before merging we should sort out the upgrade to kotlin version that's committed to master, but not fully complete / tested.

I think there are only a couple of fixes needed, but I need to find time to properly check through. Then we can see if there are any conflicts and look to merge the PR.

As well as the changes to kotlin version, there was also a change to the default supervision strategy  from One to One to Always which broke an existing test - @rogeralsing can you confirm the reasons for that - was it unrelated to the kotlin version change?

**Comment by james-cobb** [comment]
@orjan @rogeralsing I've made a PR #47 for the changes I think are needed to fix the kotlin version upgrade.

The four commits on Dec 1 & 2  look good for kotlin upgrade and refactoring, but also included a change to the default supervision strategy which I'm not sure on.

I suggest we merge this first, then look at #44 which will then have some merge issues.

**Comment by orjan** [comment]
@vito-c and @james-cobb is this still an issue or can we close the issue? It looks like #44 and #47 has been merged.

**Comment by james-cobb** [comment]
Yes #44 is merged and fixes this, closing the issue.
