### ISSUE TITLE
Release newer version

### ISSUE THREAD

**Issue by guenhter** [AsynkronIT/protoactor-kotlin#51]
A newer version of protoactor should be released (maybe when the two open pull requests #47 and #50 are merged in), because the current latest version 0.0.2 relies on pretty outdated dependencies (like coroutines) which unfortunately forces to use that old version (upgrade of coroutines would break protocactor).

**Comment by orjan** [comment]
@guenhter and @asomov how's the status of the master branch should we try adding a tag `0.0.3` to see if the publishing is still working?

**Comment by orjan** [comment]
I'll add a tag `0.0.3` it looks like `0.0.2` is broken #26

**Comment by guenhter** [comment]
@orjan I think the master branch is (or should always be) ready for release

**Comment by asomov** [comment]
I am working on extending the test suite. I do not mind to create a release to get feedback fromm the community.

**Comment by orjan** [comment]
`v0.0.5` was released yesterday and should be linked to jcenter, see #56
