### ISSUE TITLE
Are our libraries correctly pushed to jcenter?

### ISSUE THREAD

**Issue by orjan** [AsynkronIT/protoactor-kotlin#60]
For some reason there are two versions released to `springio-plugins-release`
https://github.com/AsynkronIT/protoactor-kotlin/pull/56#issuecomment-612421209
https://mvnrepository.com/artifact/actor.proto/proto-actor?repo=springio-plugins-release

**Comment by orjan** [comment]
@asomov if you look here it should be available in jcenter:
https://bintray.com/bintray/jcenter?filterByPkgName=proto-actor

Is this not working for you, try locking the dependency to `0.0.5`
https://github.com/AsynkronIT/protoactor-kotlin/blob/master/README.md#release-management

The packages are first released to `https://dl.bintray.com/asynkronit/protoactor-kotlin` and the linked to jcenter.

For the releases you was referring to I think their living in `springio-plugins-release` but I don't know how they ended up in that repo.

**Comment by asomov** [comment]
Thank you. I see it now

**Comment by orjan** [comment]
@asomov I would be great if you can verify that it's working with jcenter e.g. is this working
```
repositories {
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("actor.proto:proto-actor:0.0.5")
    implementation("actor.proto:proto-router:0.0.5")
    implementation("actor.proto:proto-remote:0.0.5")
    implementation("actor.proto:proto-mailbox:0.0.5")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}
```

I think it does but it would be great if someone else can verify it as well.
Feel free to close the issue if it's working.

**Comment by asomov** [comment]
I do not see how I can close the issue. Probably I am not authorized.
